
[tasks.build]
description = "Production ready build"
script = "fleet build --profile prod --out-dir ./build"

[tasks.start]
description = "Start the server aftear a production build"
script = "./build/"
#dependencies = ["build"]

[tasks.start-no-build]
description = "Start the server aftear a production build"
#script = "./build/"

[tasks.dev]
description = "Run the development command"
script = "fleet run"
env_files = [
   { path = ".env", profile = "development" }
]
watch = { ignore_pattern = ".*", watch = [ "./src/", ".env"] }

[tasks.test]