[debug]
address = "0.0.0.0"
port = 5000
workers = 5
keep_alive = 5
read_timeout = 5
write_timeout = 5
log_level = "normal"
limits = { forms = 32768 }

[release]
address = "0.0.0.0"
port = 8000
workers = 2
keep_alive = 5
read_timeout = 5
write_timeout = 5
log_level = "critical"